name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        # https://github.com/peaceiris/actions-gh-pages/issues/9
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_DEPLOY_KEY: ${{ secrets.actions_deploy_key }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./demo
      with:
        forceOrphan: true
